# Generated by Django 5.2.6 on 2025-11-22 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmonografias', '0007_remove_monografia_data_defesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alteracao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('REMOCAO', 'Remoção')], max_length=10)),
                ('campo_alterado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='appmonografias.banca')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Banca',
                'verbose_name_plural': 'Históricos de Bancas',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMonografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alteracao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('REMOCAO', 'Remoção')], max_length=10)),
                ('campo_alterado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='appmonografias.monografia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Monografia',
                'verbose_name_plural': 'Históricos de Monografias',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
